name: Build and Release PDF

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Python Compiler
        run: python3 main.py

      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: output.tex

      - name: Extract Short Commit SHA
        id: short_sha
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Rename PDF
        run: mv output.pdf "old-exam.pdf"

      - name: Create GitHub Release and Upload PDF
        uses: softprops/action-gh-release@v2
        with:
          tag_name: b-${{ steps.short_sha.outputs.SHORT_SHA }}
          release_name: b-${{ steps.short_sha.outputs.SHORT_SHA }}
          body: |
            This is a release of the document built from commit ${{ github.sha }}.
          files: |
            old-exam.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
